name: Android Build

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Decrypt keystore
        run: |
          openssl aes-256-cbc -K ${{ secrets.ENCRYPTED_KEYSTORE_KEY }} -iv ${{ secrets.ENCRYPTED_KEYSTORE_IV }} -in summerain0.jks.enc -out summerain0.jks -d

      - name: Accept Android SDK licenses
        run: yes | sdkmanager --licenses

      - name: Build and package Android project
        run: |
          chmod +x ./gradlew
          ./gradlew assembleRelease
          APK_NAME="云储-$(./gradlew -q printVersionName)"
          mv app/build/outputs/apk/release/app-release.apk app/build/outputs/apk/release/$APK_NAME.apk
          jarsigner -verbose -sigalg SHA256withRSA -digestalg SHA-256 -keystore summerain0.jks -storepass ${{ secrets.KEYSTORE_PASSWORD }} -keypass ${{ secrets.KEY_PASSWORD }} app/build/outputs/apk/release/$APK_NAME.apk key-alias

      - name: Upload APK artifact
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.APK_NAME }}
          path: app/build/outputs/apk/release/$APK_NAME.apk