name: Android Build

on:
  push:
    paths-ignore:
      - '**.md'
      - '**.txt'
      - '.github/**'
      - '.idea/**'
      - '!.github/workflows/**'
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'temurin'
          cache: 'gradle'

      - name: Decrypt keystore
        run: |
          openssl aes-256-cbc -K ${{ secrets.ENCRYPTED_KEYSTORE_KEY }} -iv ${{ secrets.ENCRYPTED_KEYSTORE_IV }} -in summerain0.jks.enc -out summerain0.jks -d

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Accept Android SDK licenses
        run: yes | /usr/local/lib/android/sdk/tools/bin/sdkmanager --licenses

      - name: Build Release APK
        id: build
        uses: gradle/gradle-build-action@v2.4.2
        with:
          arguments: assembleRelease

      - name: Rename APK
        run: |
          APK_NAME="云储-$(./gradlew -q printVersionName)"
          mv app/build/outputs/apk/release/app-release-unsigned.apk app/build/outputs/apk/release/$APK_NAME.apk
          echo "::set-env name=APK_NAME::$APK_NAME"

      - name: Sign APK
        run: |
          jarsigner -verbose -sigalg SHA256withRSA -digestalg SHA-256 -keystore summerain0.jks -storepass ${{ secrets.KEYSTORE_PASSWORD }} -keypass ${{ secrets.KEY_PASSWORD }} app/build/outputs/apk/release/${{ env.APK_NAME }}.apk ${{ secrets.KEY_ALIAS }}

      - name: Upload APK artifact
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.APK_NAME }}
          path: app/build/outputs/apk/release/${{ env.APK_NAME }}.apk
